Repository Seneca-CDOT/ostep-dashboard, pull requests merged in 2019-06, with the labels that each got.

#55 Clean up Osteppy server
  Osteppy/.eslintrc.json
  Osteppy/src/EODList.js
  Osteppy/src/server.js
Labels: osteppy

#68 Fix summer RA Slack ID
  Osteppy/src/EODreminder.js
Labels: bug

#71 GitHub Panel: Octocat and Details Row Fixes
  Dashboard/src/App.css
  Dashboard/src/components/Github.js
  Dashboard/src/components/Osteppy.js
Labels: bug, urgent

#69 Add Dashboard Debug Mode
  Dashboard/package.json
  Dashboard/src/Service.js
  Dashboard/src/debug/dummy-data.js
  README.md
Labels: enhancement

#78 Infrastructure Container Refactor
  Dashboard/src/components/Infrastructure.js
  Dashboard/src/debug/dummy-data.js
  Infrastructure/checkService.js
  Infrastructure/config.js
  Infrastructure/package-lock.json
  Infrastructure/package.json
  Infrastructure/server.js
  Infrastructure/servers.json
  Infrastructure/workstations.json
  package-lock.json
Labels: backend

#79 Issues/74 help wanted endpoint
  Github/package-lock.json
  Github/server.js
  Github/service.js
Labels: enhancement

#83 Issues/81 lamp status
  Dashboard/src/components/Header.js
  Github/package-lock.json
  Github/package.json
Labels: area: frontend, priority: medium, type: bug

#82 Issues/80 add technology and difficulty
  Github/service.js
Labels: priority: low, type: feature
